//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:51 PM CEST 
//


package nl.wetten.bwbng.wti;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eerstverantwoordelijke" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="afkortingen" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="afkorting" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="niet-officiele-titels" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="niet-officiele-titel" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="citeertitel" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="soort-regeling" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="identificatienummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datum-materiele-uitwerking" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element ref="{}opmerkingen" minOccurs="0"/>
 *         &lt;element name="departementaal-kenmerk" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totstandkoming" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="plaats" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="extra-informatie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rechtsgebieden" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rechtsgebied" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="hoofdgebied" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="specifiekgebied" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="overheidsdomeinen" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="overheidsdomein" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="taxonomieen" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="taxonomie" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="gegenereerd" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eerstverantwoordelijke",
    "afkortingen",
    "nietOfficieleTitels",
    "citeertitel",
    "soortRegeling",
    "identificatienummer",
    "datumMaterieleUitwerking",
    "opmerkingen",
    "departementaalKenmerk",
    "totstandkoming",
    "extraInformatie",
    "rechtsgebieden",
    "overheidsdomeinen",
    "taxonomieen"
})
@XmlRootElement(name = "algemene-informatie")
public class AlgemeneInformatie {

    @XmlElement(required = true)
    protected String eerstverantwoordelijke;
    protected AlgemeneInformatie.Afkortingen afkortingen;
    @XmlElement(name = "niet-officiele-titels")
    protected AlgemeneInformatie.NietOfficieleTitels nietOfficieleTitels;
    protected AlgemeneInformatie.Citeertitel citeertitel;
    @XmlElement(name = "soort-regeling", required = true)
    protected String soortRegeling;
    @XmlElement(required = true)
    protected String identificatienummer;
    @XmlElement(name = "datum-materiele-uitwerking")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumMaterieleUitwerking;
    protected Opmerkingen opmerkingen;
    @XmlElement(name = "departementaal-kenmerk")
    protected String departementaalKenmerk;
    protected AlgemeneInformatie.Totstandkoming totstandkoming;
    @XmlElement(name = "extra-informatie")
    protected String extraInformatie;
    protected AlgemeneInformatie.Rechtsgebieden rechtsgebieden;
    protected AlgemeneInformatie.Overheidsdomeinen overheidsdomeinen;
    protected AlgemeneInformatie.Taxonomieen taxonomieen;
    @XmlAttribute(name = "gegenereerd", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar gegenereerd;

    /**
     * Gets the value of the eerstverantwoordelijke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEerstverantwoordelijke() {
        return eerstverantwoordelijke;
    }

    /**
     * Sets the value of the eerstverantwoordelijke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEerstverantwoordelijke(String value) {
        this.eerstverantwoordelijke = value;
    }

    /**
     * Gets the value of the afkortingen property.
     * 
     * @return
     *     possible object is
     *     {@link AlgemeneInformatie.Afkortingen }
     *     
     */
    public AlgemeneInformatie.Afkortingen getAfkortingen() {
        return afkortingen;
    }

    /**
     * Sets the value of the afkortingen property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlgemeneInformatie.Afkortingen }
     *     
     */
    public void setAfkortingen(AlgemeneInformatie.Afkortingen value) {
        this.afkortingen = value;
    }

    /**
     * Gets the value of the nietOfficieleTitels property.
     * 
     * @return
     *     possible object is
     *     {@link AlgemeneInformatie.NietOfficieleTitels }
     *     
     */
    public AlgemeneInformatie.NietOfficieleTitels getNietOfficieleTitels() {
        return nietOfficieleTitels;
    }

    /**
     * Sets the value of the nietOfficieleTitels property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlgemeneInformatie.NietOfficieleTitels }
     *     
     */
    public void setNietOfficieleTitels(AlgemeneInformatie.NietOfficieleTitels value) {
        this.nietOfficieleTitels = value;
    }

    /**
     * Gets the value of the citeertitel property.
     * 
     * @return
     *     possible object is
     *     {@link AlgemeneInformatie.Citeertitel }
     *     
     */
    public AlgemeneInformatie.Citeertitel getCiteertitel() {
        return citeertitel;
    }

    /**
     * Sets the value of the citeertitel property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlgemeneInformatie.Citeertitel }
     *     
     */
    public void setCiteertitel(AlgemeneInformatie.Citeertitel value) {
        this.citeertitel = value;
    }

    /**
     * Gets the value of the soortRegeling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoortRegeling() {
        return soortRegeling;
    }

    /**
     * Sets the value of the soortRegeling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoortRegeling(String value) {
        this.soortRegeling = value;
    }

    /**
     * Gets the value of the identificatienummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificatienummer() {
        return identificatienummer;
    }

    /**
     * Sets the value of the identificatienummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificatienummer(String value) {
        this.identificatienummer = value;
    }

    /**
     * Gets the value of the datumMaterieleUitwerking property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumMaterieleUitwerking() {
        return datumMaterieleUitwerking;
    }

    /**
     * Sets the value of the datumMaterieleUitwerking property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumMaterieleUitwerking(XMLGregorianCalendar value) {
        this.datumMaterieleUitwerking = value;
    }

    /**
     * Gets the value of the opmerkingen property.
     * 
     * @return
     *     possible object is
     *     {@link Opmerkingen }
     *     
     */
    public Opmerkingen getOpmerkingen() {
        return opmerkingen;
    }

    /**
     * Sets the value of the opmerkingen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Opmerkingen }
     *     
     */
    public void setOpmerkingen(Opmerkingen value) {
        this.opmerkingen = value;
    }

    /**
     * Gets the value of the departementaalKenmerk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartementaalKenmerk() {
        return departementaalKenmerk;
    }

    /**
     * Sets the value of the departementaalKenmerk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartementaalKenmerk(String value) {
        this.departementaalKenmerk = value;
    }

    /**
     * Gets the value of the totstandkoming property.
     * 
     * @return
     *     possible object is
     *     {@link AlgemeneInformatie.Totstandkoming }
     *     
     */
    public AlgemeneInformatie.Totstandkoming getTotstandkoming() {
        return totstandkoming;
    }

    /**
     * Sets the value of the totstandkoming property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlgemeneInformatie.Totstandkoming }
     *     
     */
    public void setTotstandkoming(AlgemeneInformatie.Totstandkoming value) {
        this.totstandkoming = value;
    }

    /**
     * Gets the value of the extraInformatie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraInformatie() {
        return extraInformatie;
    }

    /**
     * Sets the value of the extraInformatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraInformatie(String value) {
        this.extraInformatie = value;
    }

    /**
     * Gets the value of the rechtsgebieden property.
     * 
     * @return
     *     possible object is
     *     {@link AlgemeneInformatie.Rechtsgebieden }
     *     
     */
    public AlgemeneInformatie.Rechtsgebieden getRechtsgebieden() {
        return rechtsgebieden;
    }

    /**
     * Sets the value of the rechtsgebieden property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlgemeneInformatie.Rechtsgebieden }
     *     
     */
    public void setRechtsgebieden(AlgemeneInformatie.Rechtsgebieden value) {
        this.rechtsgebieden = value;
    }

    /**
     * Gets the value of the overheidsdomeinen property.
     * 
     * @return
     *     possible object is
     *     {@link AlgemeneInformatie.Overheidsdomeinen }
     *     
     */
    public AlgemeneInformatie.Overheidsdomeinen getOverheidsdomeinen() {
        return overheidsdomeinen;
    }

    /**
     * Sets the value of the overheidsdomeinen property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlgemeneInformatie.Overheidsdomeinen }
     *     
     */
    public void setOverheidsdomeinen(AlgemeneInformatie.Overheidsdomeinen value) {
        this.overheidsdomeinen = value;
    }

    /**
     * Gets the value of the taxonomieen property.
     * 
     * @return
     *     possible object is
     *     {@link AlgemeneInformatie.Taxonomieen }
     *     
     */
    public AlgemeneInformatie.Taxonomieen getTaxonomieen() {
        return taxonomieen;
    }

    /**
     * Sets the value of the taxonomieen property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlgemeneInformatie.Taxonomieen }
     *     
     */
    public void setTaxonomieen(AlgemeneInformatie.Taxonomieen value) {
        this.taxonomieen = value;
    }

    /**
     * Gets the value of the gegenereerd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGegenereerd() {
        return gegenereerd;
    }

    /**
     * Sets the value of the gegenereerd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGegenereerd(XMLGregorianCalendar value) {
        this.gegenereerd = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="afkorting" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "afkorting"
    })
    public static class Afkortingen {

        @XmlElement(required = true)
        protected List<String> afkorting;

        /**
         * Gets the value of the afkorting property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the afkorting property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAfkorting().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAfkorting() {
            if (afkorting == null) {
                afkorting = new ArrayList<String>();
            }
            return this.afkorting;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Citeertitel {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "status", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String status;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="niet-officiele-titel" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nietOfficieleTitel"
    })
    public static class NietOfficieleTitels {

        @XmlElement(name = "niet-officiele-titel", required = true)
        protected List<String> nietOfficieleTitel;

        /**
         * Gets the value of the nietOfficieleTitel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nietOfficieleTitel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNietOfficieleTitel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getNietOfficieleTitel() {
            if (nietOfficieleTitel == null) {
                nietOfficieleTitel = new ArrayList<String>();
            }
            return this.nietOfficieleTitel;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="overheidsdomein" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "overheidsdomein"
    })
    public static class Overheidsdomeinen {

        @XmlElement(required = true)
        protected List<String> overheidsdomein;

        /**
         * Gets the value of the overheidsdomein property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the overheidsdomein property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOverheidsdomein().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getOverheidsdomein() {
            if (overheidsdomein == null) {
                overheidsdomein = new ArrayList<String>();
            }
            return this.overheidsdomein;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rechtsgebied" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hoofdgebied" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="specifiekgebied" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rechtsgebied"
    })
    public static class Rechtsgebieden {

        @XmlElement(required = true)
        protected List<AlgemeneInformatie.Rechtsgebieden.Rechtsgebied> rechtsgebied;

        /**
         * Gets the value of the rechtsgebied property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rechtsgebied property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRechtsgebied().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AlgemeneInformatie.Rechtsgebieden.Rechtsgebied }
         * 
         * 
         */
        public List<AlgemeneInformatie.Rechtsgebieden.Rechtsgebied> getRechtsgebied() {
            if (rechtsgebied == null) {
                rechtsgebied = new ArrayList<AlgemeneInformatie.Rechtsgebieden.Rechtsgebied>();
            }
            return this.rechtsgebied;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hoofdgebied" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="specifiekgebied" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hoofdgebied",
            "specifiekgebied"
        })
        public static class Rechtsgebied {

            @XmlElement(required = true)
            protected String hoofdgebied;
            protected String specifiekgebied;

            /**
             * Gets the value of the hoofdgebied property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHoofdgebied() {
                return hoofdgebied;
            }

            /**
             * Sets the value of the hoofdgebied property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHoofdgebied(String value) {
                this.hoofdgebied = value;
            }

            /**
             * Gets the value of the specifiekgebied property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSpecifiekgebied() {
                return specifiekgebied;
            }

            /**
             * Sets the value of the specifiekgebied property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSpecifiekgebied(String value) {
                this.specifiekgebied = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="taxonomie" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "taxonomie"
    })
    public static class Taxonomieen {

        @XmlElement(required = true)
        protected List<String> taxonomie;

        /**
         * Gets the value of the taxonomie property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the taxonomie property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTaxonomie().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getTaxonomie() {
            if (taxonomie == null) {
                taxonomie = new ArrayList<String>();
            }
            return this.taxonomie;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="plaats" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "plaats",
        "datum"
    })
    public static class Totstandkoming {

        @XmlElement(required = true)
        protected String plaats;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datum;

        /**
         * Gets the value of the plaats property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlaats() {
            return plaats;
        }

        /**
         * Sets the value of the plaats property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlaats(String value) {
            this.plaats = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatum(XMLGregorianCalendar value) {
            this.datum = value;
        }

    }

}
