//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:51 PM CEST 
//


package nl.wetten.bwbng.wti;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gerelateerd_regelingelement_parent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gerelateerd_regelingelement_parent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gerelateerd-regelingelement" type="{}gerelateerde-regeling" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gerelateerd_regelingelement_parent", propOrder = {
    "gerelateerdRegelingelement"
})
public class GerelateerdRegelingelementParent {

    @XmlElement(name = "gerelateerd-regelingelement", required = true)
    protected List<GerelateerdeRegeling> gerelateerdRegelingelement;

    /**
     * Gets the value of the gerelateerdRegelingelement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gerelateerdRegelingelement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGerelateerdRegelingelement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GerelateerdeRegeling }
     * 
     * 
     */
    public List<GerelateerdeRegeling> getGerelateerdRegelingelement() {
        if (gerelateerdRegelingelement == null) {
            gerelateerdRegelingelement = new ArrayList<GerelateerdeRegeling>();
        }
        return this.gerelateerdRegelingelement;
    }

}
