//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:51 PM CEST 
//


package nl.wetten.bwbng.wti;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kern">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://purl.org/dc/terms/}identifier"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}title"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}language"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}type" maxOccurs="unbounded"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}creator" minOccurs="0"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}modified"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}spatial" minOccurs="0"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}temporal" minOccurs="0"/>
 *                   &lt;element ref="{http://standaarden.overheid.nl/owms/terms/}authority" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="mantel" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element ref="{http://standaarden.overheid.nl/owms/terms/}abbreviation"/>
 *                   &lt;element ref="{http://standaarden.overheid.nl/owms/terms/}isRatifiedBy"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}abstract"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}accessRights"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}alternative"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}audience"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}available"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}conformsTo"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}contributor"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}coverage"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}created"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}date"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}dateAccepted"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}dateCopyrighted"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}dateSubmitted"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}description"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}educationLevel"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}extent"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}format"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}hasFormat"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}hasPart"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}hasVersion"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}instructionalMethod"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}isFormatOf"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}isPartOf"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}isReferencedBy"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}isReplacedBy"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}isRequiredBy"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}isVersionOf"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}issued"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}license"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}mediator"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}provenance"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}publisher"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}references"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}relation"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}replaces"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}requires"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}rights"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}rightsHolder"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}source"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}subject"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}tableOfContents"/>
 *                   &lt;element ref="{http://purl.org/dc/terms/}valid"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="bwb" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://standaarden.overheid.nl/owms/terms/}rechtsgebied" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{http://standaarden.overheid.nl/owms/terms/}overheidsdomein" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{http://standaarden.overheid.nl/owms/terms/}onderwerpVerdrag" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="config" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="owms-version" use="required" type="{http://www.w3.org/2001/XMLSchema}token" fixed="4.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kern",
    "mantel",
    "bwb"
})
@XmlRootElement(name = "meta", namespace = "http://standaarden.overheid.nl/bwb/owms/")
public class Meta {

    @XmlElement(namespace = "http://standaarden.overheid.nl/bwb/owms/", required = true)
    protected Meta.Kern kern;
    @XmlElement(namespace = "http://standaarden.overheid.nl/bwb/owms/")
    protected Meta.Mantel mantel;
    @XmlElement(namespace = "http://standaarden.overheid.nl/bwb/owms/")
    protected Meta.Bwb bwb;
    @XmlAttribute(name = "config")
    @XmlSchemaType(name = "anyURI")
    protected String config;
    @XmlAttribute(name = "owms-version", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String owmsVersion;

    /**
     * Gets the value of the kern property.
     * 
     * @return
     *     possible object is
     *     {@link Meta.Kern }
     *     
     */
    public Meta.Kern getKern() {
        return kern;
    }

    /**
     * Sets the value of the kern property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta.Kern }
     *     
     */
    public void setKern(Meta.Kern value) {
        this.kern = value;
    }

    /**
     * Gets the value of the mantel property.
     * 
     * @return
     *     possible object is
     *     {@link Meta.Mantel }
     *     
     */
    public Meta.Mantel getMantel() {
        return mantel;
    }

    /**
     * Sets the value of the mantel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta.Mantel }
     *     
     */
    public void setMantel(Meta.Mantel value) {
        this.mantel = value;
    }

    /**
     * Gets the value of the bwb property.
     * 
     * @return
     *     possible object is
     *     {@link Meta.Bwb }
     *     
     */
    public Meta.Bwb getBwb() {
        return bwb;
    }

    /**
     * Sets the value of the bwb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta.Bwb }
     *     
     */
    public void setBwb(Meta.Bwb value) {
        this.bwb = value;
    }

    /**
     * Gets the value of the config property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfig() {
        return config;
    }

    /**
     * Sets the value of the config property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfig(String value) {
        this.config = value;
    }

    /**
     * Gets the value of the owmsVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwmsVersion() {
        if (owmsVersion == null) {
            return "4.0";
        } else {
            return owmsVersion;
        }
    }

    /**
     * Sets the value of the owmsVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwmsVersion(String value) {
        this.owmsVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://standaarden.overheid.nl/owms/terms/}rechtsgebied" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://standaarden.overheid.nl/owms/terms/}overheidsdomein" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://standaarden.overheid.nl/owms/terms/}onderwerpVerdrag" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rechtsgebied",
        "overheidsdomein",
        "onderwerpVerdrag"
    })
    public static class Bwb {

        @XmlElement(namespace = "http://standaarden.overheid.nl/owms/terms/")
        protected List<String> rechtsgebied;
        @XmlElement(namespace = "http://standaarden.overheid.nl/owms/terms/")
        protected List<String> overheidsdomein;
        @XmlElement(namespace = "http://standaarden.overheid.nl/owms/terms/")
        protected List<String> onderwerpVerdrag;

        /**
         * Gets the value of the rechtsgebied property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rechtsgebied property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRechtsgebied().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getRechtsgebied() {
            if (rechtsgebied == null) {
                rechtsgebied = new ArrayList<String>();
            }
            return this.rechtsgebied;
        }

        /**
         * Gets the value of the overheidsdomein property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the overheidsdomein property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOverheidsdomein().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getOverheidsdomein() {
            if (overheidsdomein == null) {
                overheidsdomein = new ArrayList<String>();
            }
            return this.overheidsdomein;
        }

        /**
         * Gets the value of the onderwerpVerdrag property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the onderwerpVerdrag property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOnderwerpVerdrag().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getOnderwerpVerdrag() {
            if (onderwerpVerdrag == null) {
                onderwerpVerdrag = new ArrayList<String>();
            }
            return this.onderwerpVerdrag;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://purl.org/dc/terms/}identifier"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}title"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}language"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}type" maxOccurs="unbounded"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}creator" minOccurs="0"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}modified"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}spatial" minOccurs="0"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}temporal" minOccurs="0"/>
     *         &lt;element ref="{http://standaarden.overheid.nl/owms/terms/}authority" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identifier",
        "title",
        "language",
        "type",
        "creator",
        "modified",
        "spatial",
        "temporal",
        "authority"
    })
    public static class Kern {

        @XmlElement(namespace = "http://purl.org/dc/terms/", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String identifier;
        @XmlElement(namespace = "http://purl.org/dc/terms/", required = true)
        protected DcTermsFreeText title;
        @XmlElement(namespace = "http://purl.org/dc/terms/", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "language")
        protected String language;
        @XmlElement(namespace = "http://purl.org/dc/terms/", required = true)
        protected List<DcTermsCVorPointer> type;
        @XmlElement(namespace = "http://purl.org/dc/terms/")
        protected DcTermsCVorPointer creator;
        @XmlElement(namespace = "http://purl.org/dc/terms/", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String modified;
        @XmlElement(namespace = "http://purl.org/dc/terms/")
        protected Location spatial;
        @XmlElement(namespace = "http://purl.org/dc/terms/")
        protected PeriodOfTime temporal;
        @XmlElement(namespace = "http://standaarden.overheid.nl/owms/terms/")
        protected CVorPointer authority;

        /**
         * Gets the value of the identifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentifier() {
            return identifier;
        }

        /**
         * Sets the value of the identifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentifier(String value) {
            this.identifier = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link DcTermsFreeText }
         *     
         */
        public DcTermsFreeText getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link DcTermsFreeText }
         *     
         */
        public void setTitle(DcTermsFreeText value) {
            this.title = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the type property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DcTermsCVorPointer }
         * 
         * 
         */
        public List<DcTermsCVorPointer> getType() {
            if (type == null) {
                type = new ArrayList<DcTermsCVorPointer>();
            }
            return this.type;
        }

        /**
         * Gets the value of the creator property.
         * 
         * @return
         *     possible object is
         *     {@link DcTermsCVorPointer }
         *     
         */
        public DcTermsCVorPointer getCreator() {
            return creator;
        }

        /**
         * Sets the value of the creator property.
         * 
         * @param value
         *     allowed object is
         *     {@link DcTermsCVorPointer }
         *     
         */
        public void setCreator(DcTermsCVorPointer value) {
            this.creator = value;
        }

        /**
         * Gets the value of the modified property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModified() {
            return modified;
        }

        /**
         * Sets the value of the modified property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModified(String value) {
            this.modified = value;
        }

        /**
         * Gets the value of the spatial property.
         * 
         * @return
         *     possible object is
         *     {@link Location }
         *     
         */
        public Location getSpatial() {
            return spatial;
        }

        /**
         * Sets the value of the spatial property.
         * 
         * @param value
         *     allowed object is
         *     {@link Location }
         *     
         */
        public void setSpatial(Location value) {
            this.spatial = value;
        }

        /**
         * Gets the value of the temporal property.
         * 
         * @return
         *     possible object is
         *     {@link PeriodOfTime }
         *     
         */
        public PeriodOfTime getTemporal() {
            return temporal;
        }

        /**
         * Sets the value of the temporal property.
         * 
         * @param value
         *     allowed object is
         *     {@link PeriodOfTime }
         *     
         */
        public void setTemporal(PeriodOfTime value) {
            this.temporal = value;
        }

        /**
         * Gets the value of the authority property.
         * 
         * @return
         *     possible object is
         *     {@link CVorPointer }
         *     
         */
        public CVorPointer getAuthority() {
            return authority;
        }

        /**
         * Sets the value of the authority property.
         * 
         * @param value
         *     allowed object is
         *     {@link CVorPointer }
         *     
         */
        public void setAuthority(CVorPointer value) {
            this.authority = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element ref="{http://standaarden.overheid.nl/owms/terms/}abbreviation"/>
     *         &lt;element ref="{http://standaarden.overheid.nl/owms/terms/}isRatifiedBy"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}abstract"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}accessRights"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}alternative"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}audience"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}available"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}conformsTo"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}contributor"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}coverage"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}created"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}date"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}dateAccepted"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}dateCopyrighted"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}dateSubmitted"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}description"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}educationLevel"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}extent"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}format"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}hasFormat"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}hasPart"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}hasVersion"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}instructionalMethod"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}isFormatOf"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}isPartOf"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}isReferencedBy"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}isReplacedBy"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}isRequiredBy"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}isVersionOf"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}issued"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}license"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}mediator"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}provenance"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}publisher"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}references"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}relation"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}replaces"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}requires"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}rights"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}rightsHolder"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}source"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}subject"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}tableOfContents"/>
     *         &lt;element ref="{http://purl.org/dc/terms/}valid"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "abbreviationOrIsRatifiedByOrAbstract"
    })
    public static class Mantel {

        @XmlElementRefs({
            @XmlElementRef(name = "references", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "subject", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "license", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "tableOfContents", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "hasPart", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "publisher", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "extent", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "requires", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "audience", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "dateSubmitted", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "isReplacedBy", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "abstract", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "relation", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "alternative", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "instructionalMethod", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "accessRights", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "isReferencedBy", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "abbreviation", namespace = "http://standaarden.overheid.nl/owms/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "format", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "isRatifiedBy", namespace = "http://standaarden.overheid.nl/owms/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "source", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "replaces", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "dateAccepted", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "created", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "issued", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "description", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "provenance", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "isPartOf", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "coverage", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "rights", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "rightsHolder", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "isRequiredBy", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "date", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "hasVersion", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "mediator", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "isVersionOf", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "contributor", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "hasFormat", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "valid", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "dateCopyrighted", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "conformsTo", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "educationLevel", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "isFormatOf", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "available", namespace = "http://purl.org/dc/terms/", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<?>> abbreviationOrIsRatifiedByOrAbstract;

        /**
         * Gets the value of the abbreviationOrIsRatifiedByOrAbstract property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the abbreviationOrIsRatifiedByOrAbstract property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAbbreviationOrIsRatifiedByOrAbstract().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link TripleType }{@code >}
         * {@link JAXBElement }{@code <}{@link TripleType }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link TripleType }{@code >}
         * {@link JAXBElement }{@code <}{@link DcTermsFreeText }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link DcTermsCVorPointer }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link DcTermsFreeText }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link DcTermsFreeText }{@code >}
         * {@link JAXBElement }{@code <}{@link DcTermsFreeText }{@code >}
         * {@link JAXBElement }{@code <}{@link TripleType }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link FreeText }{@code >}
         * {@link JAXBElement }{@code <}{@link DcTermsFreeText }{@code >}
         * {@link JAXBElement }{@code <}{@link CVorPointer }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link DcTermsFreeText }{@code >}
         * {@link JAXBElement }{@code <}{@link TripleType }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link DcTermsFreeText }{@code >}
         * {@link JAXBElement }{@code <}{@link TripleType }{@code >}
         * {@link JAXBElement }{@code <}{@link TripleType }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link TripleType }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link TripleType }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link PeriodOfTime }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link DcTermsCVorPointer }{@code >}
         * {@link JAXBElement }{@code <}{@link InformationObject }{@code >}
         * {@link JAXBElement }{@code <}{@link PeriodOfTime }{@code >}
         * 
         * 
         */
        public List<JAXBElement<?>> getAbbreviationOrIsRatifiedByOrAbstract() {
            if (abbreviationOrIsRatifiedByOrAbstract == null) {
                abbreviationOrIsRatifiedByOrAbstract = new ArrayList<JAXBElement<?>>();
            }
            return this.abbreviationOrIsRatifiedByOrAbstract;
        }

    }

}
