//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:24 PM CEST 
//


package nl.wetten.bwbng.toestand;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for class.li complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="class.li">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}li.nr" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}structuur.algemeen"/>
 *           &lt;element ref="{}lokaal.structuur.li"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "class.li", propOrder = {
    "liNr",
    "structuurAlgemeenOrLokaalStructuurLi"
})
@XmlSeeAlso({
    Li.class
})
public class ClassLi {

    @XmlElement(name = "li.nr")
    protected String liNr;
    @XmlElementRefs({
        @XmlElementRef(name = "lokaal.structuur.li", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "structuur.algemeen", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> structuurAlgemeenOrLokaalStructuurLi;

    /**
     * Gets the value of the liNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiNr() {
        return liNr;
    }

    /**
     * Sets the value of the liNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiNr(String value) {
        this.liNr = value;
    }

    /**
     * Gets the value of the structuurAlgemeenOrLokaalStructuurLi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the structuurAlgemeenOrLokaalStructuurLi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStructuurAlgemeenOrLokaalStructuurLi().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Formule }{@code >}
     * {@link JAXBElement }{@code <}{@link Lijst }{@code >}
     * {@link JAXBElement }{@code <}{@link LokaalStructuurLiType }{@code >}
     * {@link JAXBElement }{@code <}{@link Plaatje }{@code >}
     * {@link JAXBElement }{@code <}{@link Al }{@code >}
     * {@link JAXBElement }{@code <}{@link Specificatielijst }{@code >}
     * {@link JAXBElement }{@code <}{@link Citaat }{@code >}
     * {@link JAXBElement }{@code <}{@link Adres }{@code >}
     * {@link JAXBElement }{@code <}{@link LokaalStructuurLiType }{@code >}
     * {@link JAXBElement }{@code <}{@link Definitielijst }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Adreslijst }{@code >}
     * {@link JAXBElement }{@code <}{@link Tussenkop }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getStructuurAlgemeenOrLokaalStructuurLi() {
        if (structuurAlgemeenOrLokaalStructuurLi == null) {
            structuurAlgemeenOrLokaalStructuurLi = new ArrayList<JAXBElement<?>>();
        }
        return this.structuurAlgemeenOrLokaalStructuurLi;
    }

}
