//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:24 PM CEST 
//


package nl.wetten.bwbng.toestand;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for class.titel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="class.titel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{}tekst.maximaal"/>
 *         &lt;group ref="{}lokaal.tekst.titel"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "class.titel", propOrder = {
    "content"
})
@XmlSeeAlso({
    Titel.class
})
public class ClassTitel {

    @XmlElementRefs({
        @XmlElementRef(name = "nadruk", type = Nadruk.class, required = false),
        @XmlElementRef(name = "tekstcorrectie", type = Tekstcorrectie.class, required = false),
        @XmlElementRef(name = "intref", type = Intref.class, required = false),
        @XmlElementRef(name = "afk", type = Afk.class, required = false),
        @XmlElementRef(name = "redactie", type = Redactie.class, required = false),
        @XmlElementRef(name = "unl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cit", type = Cit.class, required = false),
        @XmlElementRef(name = "nootref", type = Nootref.class, required = false),
        @XmlElementRef(name = "dossierref", type = Dossierref.class, required = false),
        @XmlElementRef(name = "intref-groep", type = IntrefGroep.class, required = false),
        @XmlElementRef(name = "indexterm", type = Indexterm.class, required = false),
        @XmlElementRef(name = "dfn", type = Dfn.class, required = false),
        @XmlElementRef(name = "omissie", type = Omissie.class, required = false),
        @XmlElementRef(name = "sup", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "noot", type = Noot.class, required = false),
        @XmlElementRef(name = "extref", type = Extref.class, required = false),
        @XmlElementRef(name = "ovl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "aanhaling", type = Aanhaling.class, required = false),
        @XmlElementRef(name = "inf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "extref-groep", type = ExtrefGroep.class, required = false)
    })
    @XmlMixed
    protected List<Object> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Nadruk }
     * {@link Tekstcorrectie }
     * {@link Intref }
     * {@link Afk }
     * {@link Redactie }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Cit }
     * {@link Nootref }
     * {@link Dossierref }
     * {@link IntrefGroep }
     * {@link Indexterm }
     * {@link Dfn }
     * {@link Omissie }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Noot }
     * {@link Extref }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Aanhaling }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link ExtrefGroep }
     * {@link String }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
