//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:24 PM CEST 
//


package nl.wetten.bwbng.toestand;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for class.bijlage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="class.bijlage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}kop" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;group ref="{}structuur.maximaal"/>
 *           &lt;element ref="{}divisie"/>
 *           &lt;group ref="{}lokaal.structuur.bijlage"/>
 *         &lt;/choice>
 *         &lt;element ref="{}bijlage-sluiting" minOccurs="0"/>
 *         &lt;group ref="{}lokaal.structuur.formeel"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "class.bijlage", propOrder = {
    "kop",
    "structuurAlgemeenOrTableOrDivisie",
    "bijlageSluiting",
    "metaData"
})
@XmlSeeAlso({
    Bijlage.class
})
public class ClassBijlage {

    protected Kop kop;
    @XmlElementRefs({
        @XmlElementRef(name = "artikel", type = Artikel.class, required = false),
        @XmlElementRef(name = "structuur.algemeen", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "divisie", type = Divisie.class, required = false),
        @XmlElementRef(name = "model", type = Model.class, required = false),
        @XmlElementRef(name = "table", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "wetcitaat", type = Wetcitaat.class, required = false),
        @XmlElementRef(name = "officiele-inhoudsopgave", type = OfficieleInhoudsopgave.class, required = false)
    })
    protected List<Object> structuurAlgemeenOrTableOrDivisie;
    @XmlElement(name = "bijlage-sluiting")
    protected BijlageSluiting bijlageSluiting;
    @XmlElement(name = "meta-data")
    protected MetaData metaData;

    /**
     * Gets the value of the kop property.
     * 
     * @return
     *     possible object is
     *     {@link Kop }
     *     
     */
    public Kop getKop() {
        return kop;
    }

    /**
     * Sets the value of the kop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kop }
     *     
     */
    public void setKop(Kop value) {
        this.kop = value;
    }

    /**
     * Gets the value of the structuurAlgemeenOrTableOrDivisie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the structuurAlgemeenOrTableOrDivisie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStructuurAlgemeenOrTableOrDivisie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Formule }{@code >}
     * {@link JAXBElement }{@code <}{@link Lijst }{@code >}
     * {@link JAXBElement }{@code <}{@link Plaatje }{@code >}
     * {@link Artikel }
     * {@link JAXBElement }{@code <}{@link Al }{@code >}
     * {@link Divisie }
     * {@link JAXBElement }{@code <}{@link Specificatielijst }{@code >}
     * {@link JAXBElement }{@code <}{@link Citaat }{@code >}
     * {@link JAXBElement }{@code <}{@link Adres }{@code >}
     * {@link JAXBElement }{@code <}{@link LokaalStructuurLiType }{@code >}
     * {@link Wetcitaat }
     * {@link OfficieleInhoudsopgave }
     * {@link JAXBElement }{@code <}{@link Definitielijst }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link Model }
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Adreslijst }{@code >}
     * {@link JAXBElement }{@code <}{@link Tussenkop }{@code >}
     * 
     * 
     */
    public List<Object> getStructuurAlgemeenOrTableOrDivisie() {
        if (structuurAlgemeenOrTableOrDivisie == null) {
            structuurAlgemeenOrTableOrDivisie = new ArrayList<Object>();
        }
        return this.structuurAlgemeenOrTableOrDivisie;
    }

    /**
     * Gets the value of the bijlageSluiting property.
     * 
     * @return
     *     possible object is
     *     {@link BijlageSluiting }
     *     
     */
    public BijlageSluiting getBijlageSluiting() {
        return bijlageSluiting;
    }

    /**
     * Sets the value of the bijlageSluiting property.
     * 
     * @param value
     *     allowed object is
     *     {@link BijlageSluiting }
     *     
     */
    public void setBijlageSluiting(BijlageSluiting value) {
        this.bijlageSluiting = value;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link MetaData }
     *     
     */
    public MetaData getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaData }
     *     
     */
    public void setMetaData(MetaData value) {
        this.metaData = value;
    }

}
