//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:24 PM CEST 
//


package nl.wetten.bwbng.toestand;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for class.wetsluiting complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="class.wetsluiting">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}slotformulering" minOccurs="0"/>
 *         &lt;element ref="{}gegeven" minOccurs="0"/>
 *         &lt;element ref="{}ondertekening" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}uitgifte" minOccurs="0"/>
 *         &lt;group ref="{}lokaal.structuur.formeel"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "class.wetsluiting", propOrder = {
    "slotformulering",
    "gegeven",
    "ondertekening",
    "uitgifte",
    "metaData"
})
@XmlSeeAlso({
    Wetsluiting.class
})
public class ClassWetsluiting {

    protected Slotformulering slotformulering;
    protected Gegeven gegeven;
    protected List<ClassOndertekening> ondertekening;
    protected Uitgifte uitgifte;
    @XmlElement(name = "meta-data")
    protected MetaData metaData;

    /**
     * Gets the value of the slotformulering property.
     * 
     * @return
     *     possible object is
     *     {@link Slotformulering }
     *     
     */
    public Slotformulering getSlotformulering() {
        return slotformulering;
    }

    /**
     * Sets the value of the slotformulering property.
     * 
     * @param value
     *     allowed object is
     *     {@link Slotformulering }
     *     
     */
    public void setSlotformulering(Slotformulering value) {
        this.slotformulering = value;
    }

    /**
     * Gets the value of the gegeven property.
     * 
     * @return
     *     possible object is
     *     {@link Gegeven }
     *     
     */
    public Gegeven getGegeven() {
        return gegeven;
    }

    /**
     * Sets the value of the gegeven property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gegeven }
     *     
     */
    public void setGegeven(Gegeven value) {
        this.gegeven = value;
    }

    /**
     * Gets the value of the ondertekening property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ondertekening property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOndertekening().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassOndertekening }
     * 
     * 
     */
    public List<ClassOndertekening> getOndertekening() {
        if (ondertekening == null) {
            ondertekening = new ArrayList<ClassOndertekening>();
        }
        return this.ondertekening;
    }

    /**
     * Gets the value of the uitgifte property.
     * 
     * @return
     *     possible object is
     *     {@link Uitgifte }
     *     
     */
    public Uitgifte getUitgifte() {
        return uitgifte;
    }

    /**
     * Sets the value of the uitgifte property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uitgifte }
     *     
     */
    public void setUitgifte(Uitgifte value) {
        this.uitgifte = value;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link MetaData }
     *     
     */
    public MetaData getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaData }
     *     
     */
    public void setMetaData(MetaData value) {
        this.metaData = value;
    }

}
