//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:24 PM CEST 
//


package nl.wetten.bwbng.toestand;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3c.dom.Element;


/**
 * <p>Java class for class.meta-data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="class.meta-data">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}brondata" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="terugwerkende-kracht-data" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="terugwerkende-kracht">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="terugwerkend.datum">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="datum-scope" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                     &lt;attribute name="isodatum" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="terugwerkende-kracht-opmerkingen">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attGroup ref="{}attlist.terugwerkende-kracht"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}historische-brondata" minOccurs="0"/>
 *         &lt;element ref="{}redactioneel" minOccurs="0"/>
 *         &lt;element ref="{}delegatie" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "class.meta-data", propOrder = {
    "brondata",
    "terugwerkendeKrachtData",
    "historischeBrondata",
    "redactioneel",
    "delegatie"
})
@XmlSeeAlso({
    MetaData.class
})
public class ClassMetaData {

    protected List<Brondata> brondata;
    @XmlElement(name = "terugwerkende-kracht-data")
    protected ClassMetaData.TerugwerkendeKrachtData terugwerkendeKrachtData;
    @XmlElement(name = "historische-brondata")
    protected HistorischeBrondata historischeBrondata;
    protected Redactioneel redactioneel;
    protected Delegatie delegatie;

    /**
     * Gets the value of the brondata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the brondata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBrondata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Brondata }
     * 
     * 
     */
    public List<Brondata> getBrondata() {
        if (brondata == null) {
            brondata = new ArrayList<Brondata>();
        }
        return this.brondata;
    }

    /**
     * Gets the value of the terugwerkendeKrachtData property.
     * 
     * @return
     *     possible object is
     *     {@link ClassMetaData.TerugwerkendeKrachtData }
     *     
     */
    public ClassMetaData.TerugwerkendeKrachtData getTerugwerkendeKrachtData() {
        return terugwerkendeKrachtData;
    }

    /**
     * Sets the value of the terugwerkendeKrachtData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassMetaData.TerugwerkendeKrachtData }
     *     
     */
    public void setTerugwerkendeKrachtData(ClassMetaData.TerugwerkendeKrachtData value) {
        this.terugwerkendeKrachtData = value;
    }

    /**
     * Gets the value of the historischeBrondata property.
     * 
     * @return
     *     possible object is
     *     {@link HistorischeBrondata }
     *     
     */
    public HistorischeBrondata getHistorischeBrondata() {
        return historischeBrondata;
    }

    /**
     * Sets the value of the historischeBrondata property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistorischeBrondata }
     *     
     */
    public void setHistorischeBrondata(HistorischeBrondata value) {
        this.historischeBrondata = value;
    }

    /**
     * Gets the value of the redactioneel property.
     * 
     * @return
     *     possible object is
     *     {@link Redactioneel }
     *     
     */
    public Redactioneel getRedactioneel() {
        return redactioneel;
    }

    /**
     * Sets the value of the redactioneel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Redactioneel }
     *     
     */
    public void setRedactioneel(Redactioneel value) {
        this.redactioneel = value;
    }

    /**
     * Gets the value of the delegatie property.
     * 
     * @return
     *     possible object is
     *     {@link Delegatie }
     *     
     */
    public Delegatie getDelegatie() {
        return delegatie;
    }

    /**
     * Sets the value of the delegatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Delegatie }
     *     
     */
    public void setDelegatie(Delegatie value) {
        this.delegatie = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="terugwerkende-kracht">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="terugwerkend.datum">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="datum-scope" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                           &lt;attribute name="isodatum" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="terugwerkende-kracht-opmerkingen">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attGroup ref="{}attlist.terugwerkende-kracht"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "terugwerkendeKracht"
    })
    public static class TerugwerkendeKrachtData {

        @XmlElement(name = "terugwerkende-kracht", required = true)
        protected List<ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht> terugwerkendeKracht;

        /**
         * Gets the value of the terugwerkendeKracht property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the terugwerkendeKracht property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTerugwerkendeKracht().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht }
         * 
         * 
         */
        public List<ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht> getTerugwerkendeKracht() {
            if (terugwerkendeKracht == null) {
                terugwerkendeKracht = new ArrayList<ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht>();
            }
            return this.terugwerkendeKracht;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="terugwerkend.datum">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="datum-scope" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                 &lt;attribute name="isodatum" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="terugwerkende-kracht-opmerkingen">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attGroup ref="{}attlist.terugwerkende-kracht"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "terugwerkendDatum",
            "terugwerkendeKrachtOpmerkingen"
        })
        public static class TerugwerkendeKracht {

            @XmlElement(name = "terugwerkend.datum", required = true)
            protected ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht.TerugwerkendDatum terugwerkendDatum;
            @XmlElement(name = "terugwerkende-kracht-opmerkingen", required = true)
            protected ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht.TerugwerkendeKrachtOpmerkingen terugwerkendeKrachtOpmerkingen;
            @XmlAttribute(name = "terugwerking")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar terugwerking;

            /**
             * Gets the value of the terugwerkendDatum property.
             * 
             * @return
             *     possible object is
             *     {@link ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht.TerugwerkendDatum }
             *     
             */
            public ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht.TerugwerkendDatum getTerugwerkendDatum() {
                return terugwerkendDatum;
            }

            /**
             * Sets the value of the terugwerkendDatum property.
             * 
             * @param value
             *     allowed object is
             *     {@link ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht.TerugwerkendDatum }
             *     
             */
            public void setTerugwerkendDatum(ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht.TerugwerkendDatum value) {
                this.terugwerkendDatum = value;
            }

            /**
             * Gets the value of the terugwerkendeKrachtOpmerkingen property.
             * 
             * @return
             *     possible object is
             *     {@link ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht.TerugwerkendeKrachtOpmerkingen }
             *     
             */
            public ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht.TerugwerkendeKrachtOpmerkingen getTerugwerkendeKrachtOpmerkingen() {
                return terugwerkendeKrachtOpmerkingen;
            }

            /**
             * Sets the value of the terugwerkendeKrachtOpmerkingen property.
             * 
             * @param value
             *     allowed object is
             *     {@link ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht.TerugwerkendeKrachtOpmerkingen }
             *     
             */
            public void setTerugwerkendeKrachtOpmerkingen(ClassMetaData.TerugwerkendeKrachtData.TerugwerkendeKracht.TerugwerkendeKrachtOpmerkingen value) {
                this.terugwerkendeKrachtOpmerkingen = value;
            }

            /**
             * Gets the value of the terugwerking property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTerugwerking() {
                return terugwerking;
            }

            /**
             * Sets the value of the terugwerking property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTerugwerking(XMLGregorianCalendar value) {
                this.terugwerking = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="datum-scope" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *       &lt;attribute name="isodatum" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class TerugwerkendDatum {

                @XmlValue
                protected String content;
                @XmlAttribute(name = "datum-scope")
                @XmlSchemaType(name = "anySimpleType")
                protected String datumScope;
                @XmlAttribute(name = "isodatum")
                @XmlSchemaType(name = "anySimpleType")
                protected String isodatum;

                /**
                 * Gets the value of the content property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContent() {
                    return content;
                }

                /**
                 * Sets the value of the content property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContent(String value) {
                    this.content = value;
                }

                /**
                 * Gets the value of the datumScope property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDatumScope() {
                    return datumScope;
                }

                /**
                 * Sets the value of the datumScope property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDatumScope(String value) {
                    this.datumScope = value;
                }

                /**
                 * Gets the value of the isodatum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIsodatum() {
                    return isodatum;
                }

                /**
                 * Sets the value of the isodatum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIsodatum(String value) {
                    this.isodatum = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "any"
            })
            public static class TerugwerkendeKrachtOpmerkingen {

                @XmlAnyElement
                protected List<Element> any;

                /**
                 * Gets the value of the any property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the any property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAny().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Element }
                 * 
                 * 
                 */
                public List<Element> getAny() {
                    if (any == null) {
                        any = new ArrayList<Element>();
                    }
                    return this.any;
                }

            }

        }

    }

}
