//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:24 PM CEST 
//


package nl.wetten.bwbng.toestand;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for class.deel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="class.deel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}kop"/>
 *         &lt;element ref="{}officiele-inhoudsopgave" minOccurs="0"/>
 *         &lt;element ref="{}structuurtekst" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}hoofdstuk"/>
 *           &lt;element ref="{}titeldeel"/>
 *           &lt;element ref="{}afdeling"/>
 *           &lt;element ref="{}paragraaf"/>
 *           &lt;element ref="{}artikel"/>
 *           &lt;element ref="{}lokaal.structuur.wetgeving"/>
 *         &lt;/choice>
 *         &lt;group ref="{}lokaal.structuur.formeel"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "class.deel", propOrder = {
    "kop",
    "officieleInhoudsopgave",
    "structuurtekst",
    "hoofdstukOrTiteldeelOrAfdeling",
    "metaData"
})
@XmlSeeAlso({
    Deel.class
})
public class ClassDeel {

    @XmlElement(required = true)
    protected Kop kop;
    @XmlElement(name = "officiele-inhoudsopgave")
    protected OfficieleInhoudsopgave officieleInhoudsopgave;
    protected Structuurtekst structuurtekst;
    @XmlElementRefs({
        @XmlElementRef(name = "titeldeel", type = Titeldeel.class, required = false),
        @XmlElementRef(name = "hoofdstuk", type = Hoofdstuk.class, required = false),
        @XmlElementRef(name = "afdeling", type = Afdeling.class, required = false),
        @XmlElementRef(name = "paragraaf", type = Paragraaf.class, required = false),
        @XmlElementRef(name = "artikel", type = Artikel.class, required = false),
        @XmlElementRef(name = "lokaal.structuur.wetgeving", type = JAXBElement.class, required = false)
    })
    protected List<Object> hoofdstukOrTiteldeelOrAfdeling;
    @XmlElement(name = "meta-data")
    protected MetaData metaData;

    /**
     * Gets the value of the kop property.
     * 
     * @return
     *     possible object is
     *     {@link Kop }
     *     
     */
    public Kop getKop() {
        return kop;
    }

    /**
     * Sets the value of the kop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kop }
     *     
     */
    public void setKop(Kop value) {
        this.kop = value;
    }

    /**
     * Gets the value of the officieleInhoudsopgave property.
     * 
     * @return
     *     possible object is
     *     {@link OfficieleInhoudsopgave }
     *     
     */
    public OfficieleInhoudsopgave getOfficieleInhoudsopgave() {
        return officieleInhoudsopgave;
    }

    /**
     * Sets the value of the officieleInhoudsopgave property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfficieleInhoudsopgave }
     *     
     */
    public void setOfficieleInhoudsopgave(OfficieleInhoudsopgave value) {
        this.officieleInhoudsopgave = value;
    }

    /**
     * Gets the value of the structuurtekst property.
     * 
     * @return
     *     possible object is
     *     {@link Structuurtekst }
     *     
     */
    public Structuurtekst getStructuurtekst() {
        return structuurtekst;
    }

    /**
     * Sets the value of the structuurtekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Structuurtekst }
     *     
     */
    public void setStructuurtekst(Structuurtekst value) {
        this.structuurtekst = value;
    }

    /**
     * Gets the value of the hoofdstukOrTiteldeelOrAfdeling property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hoofdstukOrTiteldeelOrAfdeling property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHoofdstukOrTiteldeelOrAfdeling().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Titeldeel }
     * {@link Hoofdstuk }
     * {@link Afdeling }
     * {@link Paragraaf }
     * {@link Artikel }
     * {@link JAXBElement }{@code <}{@link LokaalStructuurWetgeving }{@code >}
     * {@link JAXBElement }{@code <}{@link LokaalStructuurWetgeving }{@code >}
     * 
     * 
     */
    public List<Object> getHoofdstukOrTiteldeelOrAfdeling() {
        if (hoofdstukOrTiteldeelOrAfdeling == null) {
            hoofdstukOrTiteldeelOrAfdeling = new ArrayList<Object>();
        }
        return this.hoofdstukOrTiteldeelOrAfdeling;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link MetaData }
     *     
     */
    public MetaData getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaData }
     *     
     */
    public void setMetaData(MetaData value) {
        this.metaData = value;
    }

}
