//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:24 PM CEST 
//


package nl.wetten.bwbng.toestand;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}plaats"/>
 *           &lt;element ref="{}actie"/>
 *         &lt;/choice>
 *         &lt;element ref="{}datum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "plaats",
    "actie",
    "datum"
})
@XmlRootElement(name = "dagtekening")
public class Dagtekening {

    protected Plaats plaats;
    protected String actie;
    @XmlElement(required = true)
    protected Datum datum;

    /**
     * Gets the value of the plaats property.
     * 
     * @return
     *     possible object is
     *     {@link Plaats }
     *     
     */
    public Plaats getPlaats() {
        return plaats;
    }

    /**
     * Sets the value of the plaats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Plaats }
     *     
     */
    public void setPlaats(Plaats value) {
        this.plaats = value;
    }

    /**
     * Gets the value of the actie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActie() {
        return actie;
    }

    /**
     * Sets the value of the actie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActie(String value) {
        this.actie = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link Datum }
     *     
     */
    public Datum getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datum }
     *     
     */
    public void setDatum(Datum value) {
        this.datum = value;
    }

}
