//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:24 PM CEST 
//


package nl.wetten.bwbng.toestand;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.illustratie"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "illustratie")
public class Illustratie {

    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "naam", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String naam;
    @XmlAttribute(name = "alt")
    protected String alt;
    @XmlAttribute(name = "display")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String display;
    @XmlAttribute(name = "breedte")
    @XmlSchemaType(name = "anySimpleType")
    protected String breedte;
    @XmlAttribute(name = "hoogte")
    @XmlSchemaType(name = "anySimpleType")
    protected String hoogte;
    @XmlAttribute(name = "xoffset")
    @XmlSchemaType(name = "anySimpleType")
    protected String xoffset;
    @XmlAttribute(name = "yoffset")
    @XmlSchemaType(name = "anySimpleType")
    protected String yoffset;
    @XmlAttribute(name = "rotatie")
    @XmlSchemaType(name = "anySimpleType")
    protected String rotatie;
    @XmlAttribute(name = "schaal")
    @XmlSchemaType(name = "anySimpleType")
    protected String schaal;
    @XmlAttribute(name = "uitlijning")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String uitlijning;
    @XmlAttribute(name = "resolutie")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String resolutie;
    @XmlAttribute(name = "kleur")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String kleur;
    @XmlAttribute(name = "formaat")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String formaat;
    @XmlAttribute(name = "type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the naam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaam() {
        return naam;
    }

    /**
     * Sets the value of the naam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaam(String value) {
        this.naam = value;
    }

    /**
     * Gets the value of the alt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlt() {
        return alt;
    }

    /**
     * Sets the value of the alt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlt(String value) {
        this.alt = value;
    }

    /**
     * Gets the value of the display property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplay() {
        if (display == null) {
            return "block";
        } else {
            return display;
        }
    }

    /**
     * Sets the value of the display property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplay(String value) {
        this.display = value;
    }

    /**
     * Gets the value of the breedte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreedte() {
        return breedte;
    }

    /**
     * Sets the value of the breedte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreedte(String value) {
        this.breedte = value;
    }

    /**
     * Gets the value of the hoogte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoogte() {
        return hoogte;
    }

    /**
     * Sets the value of the hoogte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoogte(String value) {
        this.hoogte = value;
    }

    /**
     * Gets the value of the xoffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXoffset() {
        return xoffset;
    }

    /**
     * Sets the value of the xoffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXoffset(String value) {
        this.xoffset = value;
    }

    /**
     * Gets the value of the yoffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYoffset() {
        return yoffset;
    }

    /**
     * Sets the value of the yoffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYoffset(String value) {
        this.yoffset = value;
    }

    /**
     * Gets the value of the rotatie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRotatie() {
        return rotatie;
    }

    /**
     * Sets the value of the rotatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRotatie(String value) {
        this.rotatie = value;
    }

    /**
     * Gets the value of the schaal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchaal() {
        return schaal;
    }

    /**
     * Sets the value of the schaal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchaal(String value) {
        this.schaal = value;
    }

    /**
     * Gets the value of the uitlijning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUitlijning() {
        if (uitlijning == null) {
            return "start";
        } else {
            return uitlijning;
        }
    }

    /**
     * Sets the value of the uitlijning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUitlijning(String value) {
        this.uitlijning = value;
    }

    /**
     * Gets the value of the resolutie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResolutie() {
        return resolutie;
    }

    /**
     * Sets the value of the resolutie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResolutie(String value) {
        this.resolutie = value;
    }

    /**
     * Gets the value of the kleur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKleur() {
        if (kleur == null) {
            return "nee";
        } else {
            return kleur;
        }
    }

    /**
     * Sets the value of the kleur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKleur(String value) {
        this.kleur = value;
    }

    /**
     * Gets the value of the formaat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormaat() {
        if (formaat == null) {
            return "eps";
        } else {
            return formaat;
        }
    }

    /**
     * Sets the value of the formaat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormaat(String value) {
        this.formaat = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
