//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:24 PM CEST 
//


package nl.wetten.bwbng.toestand;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}enig-artikel"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}hoofdstuk"/>
 *           &lt;element ref="{}paragraaf"/>
 *           &lt;element ref="{}artikel"/>
 *           &lt;element ref="{}wijzig-artikel"/>
 *         &lt;/choice>
 *         &lt;element ref="{}tekst"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{}attlist.regeling-tekst"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "enigArtikel",
    "hoofdstukOrParagraafOrArtikel",
    "tekst"
})
@XmlRootElement(name = "regeling-tekst")
public class RegelingTekst {

    @XmlElement(name = "enig-artikel")
    protected EnigArtikel enigArtikel;
    @XmlElements({
        @XmlElement(name = "hoofdstuk", type = Hoofdstuk.class),
        @XmlElement(name = "paragraaf", type = Paragraaf.class),
        @XmlElement(name = "artikel", type = Artikel.class),
        @XmlElement(name = "wijzig-artikel", type = LokaalStructuurWetgeving.class)
    })
    protected List<Object> hoofdstukOrParagraafOrArtikel;
    protected Tekst tekst;

    /**
     * Gets the value of the enigArtikel property.
     * 
     * @return
     *     possible object is
     *     {@link EnigArtikel }
     *     
     */
    public EnigArtikel getEnigArtikel() {
        return enigArtikel;
    }

    /**
     * Sets the value of the enigArtikel property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnigArtikel }
     *     
     */
    public void setEnigArtikel(EnigArtikel value) {
        this.enigArtikel = value;
    }

    /**
     * Gets the value of the hoofdstukOrParagraafOrArtikel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hoofdstukOrParagraafOrArtikel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHoofdstukOrParagraafOrArtikel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hoofdstuk }
     * {@link Paragraaf }
     * {@link Artikel }
     * {@link LokaalStructuurWetgeving }
     * 
     * 
     */
    public List<Object> getHoofdstukOrParagraafOrArtikel() {
        if (hoofdstukOrParagraafOrArtikel == null) {
            hoofdstukOrParagraafOrArtikel = new ArrayList<Object>();
        }
        return this.hoofdstukOrParagraafOrArtikel;
    }

    /**
     * Gets the value of the tekst property.
     * 
     * @return
     *     possible object is
     *     {@link Tekst }
     *     
     */
    public Tekst getTekst() {
        return tekst;
    }

    /**
     * Sets the value of the tekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tekst }
     *     
     */
    public void setTekst(Tekst value) {
        this.tekst = value;
    }

}
