//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:24 PM CEST 
//


package nl.wetten.bwbng.toestand;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}aanhef" minOccurs="0"/>
 *         &lt;element ref="{}wettekst"/>
 *         &lt;element ref="{}wetsluiting" minOccurs="0"/>
 *         &lt;element ref="{}officiele-inhoudsopgave" minOccurs="0"/>
 *         &lt;element ref="{}bijlage" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.wet-besluit"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aanhef",
    "wettekst",
    "wetsluiting",
    "officieleInhoudsopgave",
    "bijlage"
})
@XmlRootElement(name = "wet-besluit")
public class WetBesluit {

    protected Aanhef aanhef;
    @XmlElement(required = true)
    protected Wettekst wettekst;
    protected Wetsluiting wetsluiting;
    @XmlElement(name = "officiele-inhoudsopgave")
    protected OfficieleInhoudsopgave officieleInhoudsopgave;
    protected List<Bijlage> bijlage;

    /**
     * Gets the value of the aanhef property.
     * 
     * @return
     *     possible object is
     *     {@link Aanhef }
     *     
     */
    public Aanhef getAanhef() {
        return aanhef;
    }

    /**
     * Sets the value of the aanhef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aanhef }
     *     
     */
    public void setAanhef(Aanhef value) {
        this.aanhef = value;
    }

    /**
     * Gets the value of the wettekst property.
     * 
     * @return
     *     possible object is
     *     {@link Wettekst }
     *     
     */
    public Wettekst getWettekst() {
        return wettekst;
    }

    /**
     * Sets the value of the wettekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wettekst }
     *     
     */
    public void setWettekst(Wettekst value) {
        this.wettekst = value;
    }

    /**
     * Gets the value of the wetsluiting property.
     * 
     * @return
     *     possible object is
     *     {@link Wetsluiting }
     *     
     */
    public Wetsluiting getWetsluiting() {
        return wetsluiting;
    }

    /**
     * Sets the value of the wetsluiting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wetsluiting }
     *     
     */
    public void setWetsluiting(Wetsluiting value) {
        this.wetsluiting = value;
    }

    /**
     * Gets the value of the officieleInhoudsopgave property.
     * 
     * @return
     *     possible object is
     *     {@link OfficieleInhoudsopgave }
     *     
     */
    public OfficieleInhoudsopgave getOfficieleInhoudsopgave() {
        return officieleInhoudsopgave;
    }

    /**
     * Sets the value of the officieleInhoudsopgave property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfficieleInhoudsopgave }
     *     
     */
    public void setOfficieleInhoudsopgave(OfficieleInhoudsopgave value) {
        this.officieleInhoudsopgave = value;
    }

    /**
     * Gets the value of the bijlage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bijlage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBijlage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bijlage }
     * 
     * 
     */
    public List<Bijlage> getBijlage() {
        if (bijlage == null) {
            bijlage = new ArrayList<Bijlage>();
        }
        return this.bijlage;
    }

}
