//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:24 PM CEST 
//


package nl.wetten.bwbng.toestand;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}publicatie" minOccurs="0"/>
 *         &lt;element ref="{}verdragspartijen" minOccurs="0"/>
 *         &lt;element ref="{}commentaar-wetgeving" minOccurs="0"/>
 *         &lt;element ref="{}geschiedenis" minOccurs="0"/>
 *         &lt;element ref="{}parlementair" minOccurs="0"/>
 *         &lt;element ref="{}eerst-verantwoordelijk" minOccurs="0"/>
 *         &lt;element ref="{}materiele-uitwerkingtreding.datum" minOccurs="0"/>
 *         &lt;element ref="{}origine" minOccurs="0"/>
 *         &lt;element ref="{}grondslagen" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}vertaling-van" maxOccurs="unbounded"/>
 *           &lt;element ref="{}vertaald-door"/>
 *         &lt;/choice>
 *         &lt;element ref="{}totstandkoming" minOccurs="0"/>
 *         &lt;element ref="{}alias-titels" minOccurs="0"/>
 *         &lt;element ref="{}intitule"/>
 *         &lt;element ref="{}citeertitel"/>
 *         &lt;choice>
 *           &lt;element ref="{}wet-besluit"/>
 *           &lt;element ref="{}regeling"/>
 *           &lt;element ref="{}circulaire"/>
 *           &lt;element ref="{}verdrag" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{}meta-data" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.wetgeving"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "publicatie",
    "verdragspartijen",
    "commentaarWetgeving",
    "geschiedenis",
    "parlementair",
    "eerstVerantwoordelijk",
    "materieleUitwerkingtredingDatum",
    "origine",
    "grondslagen",
    "vertalingVan",
    "vertaaldDoor",
    "totstandkoming",
    "aliasTitels",
    "intitule",
    "citeertitel",
    "wetBesluit",
    "regeling",
    "circulaire",
    "verdrag",
    "metaData"
})
@XmlRootElement(name = "wetgeving")
public class Wetgeving {

    protected Publicatie publicatie;
    protected Verdragspartijen verdragspartijen;
    @XmlElement(name = "commentaar-wetgeving")
    protected CommentaarWetgeving commentaarWetgeving;
    protected Geschiedenis geschiedenis;
    protected Parlementair parlementair;
    @XmlElement(name = "eerst-verantwoordelijk")
    protected EerstVerantwoordelijk eerstVerantwoordelijk;
    @XmlElement(name = "materiele-uitwerkingtreding.datum")
    protected MaterieleUitwerkingtredingDatum materieleUitwerkingtredingDatum;
    protected String origine;
    protected Grondslagen grondslagen;
    @XmlElement(name = "vertaling-van")
    protected List<VertalingVan> vertalingVan;
    @XmlElement(name = "vertaald-door")
    protected VertaaldDoor vertaaldDoor;
    protected Totstandkoming totstandkoming;
    @XmlElement(name = "alias-titels")
    protected AliasTitels aliasTitels;
    @XmlElement(required = true)
    protected Intitule intitule;
    @XmlElement(required = true)
    protected Citeertitel citeertitel;
    @XmlElement(name = "wet-besluit")
    protected WetBesluit wetBesluit;
    protected Regeling regeling;
    protected Circulaire circulaire;
    protected List<Verdrag> verdrag;
    @XmlElement(name = "meta-data")
    protected MetaData metaData;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "dtdversie")
    protected String dtdversie;
    @XmlAttribute(name = "sleutel")
    @XmlSchemaType(name = "anySimpleType")
    protected String sleutel;
    @XmlAttribute(name = "soort")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String soort;
    @XmlAttribute(name = "label-id")
    @XmlSchemaType(name = "anySimpleType")
    protected String labelId;
    @XmlAttribute(name = "stam-id")
    @XmlSchemaType(name = "anySimpleType")
    protected String stamId;
    @XmlAttribute(name = "versie-id")
    @XmlSchemaType(name = "anySimpleType")
    protected String versieId;
    @XmlAttribute(name = "verdragnummer")
    @XmlSchemaType(name = "anySimpleType")
    protected String verdragnummer;
    @XmlAttribute(name = "publicatie")
    @XmlSchemaType(name = "anySimpleType")
    protected String publicatieAttr;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lang;

    /**
     * Gets the value of the publicatie property.
     * 
     * @return
     *     possible object is
     *     {@link Publicatie }
     *     
     */
    public Publicatie getPublicatie() {
        return publicatie;
    }

    /**
     * Sets the value of the publicatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publicatie }
     *     
     */
    public void setPublicatie(Publicatie value) {
        this.publicatie = value;
    }

    /**
     * Gets the value of the verdragspartijen property.
     * 
     * @return
     *     possible object is
     *     {@link Verdragspartijen }
     *     
     */
    public Verdragspartijen getVerdragspartijen() {
        return verdragspartijen;
    }

    /**
     * Sets the value of the verdragspartijen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Verdragspartijen }
     *     
     */
    public void setVerdragspartijen(Verdragspartijen value) {
        this.verdragspartijen = value;
    }

    /**
     * Gets the value of the commentaarWetgeving property.
     * 
     * @return
     *     possible object is
     *     {@link CommentaarWetgeving }
     *     
     */
    public CommentaarWetgeving getCommentaarWetgeving() {
        return commentaarWetgeving;
    }

    /**
     * Sets the value of the commentaarWetgeving property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentaarWetgeving }
     *     
     */
    public void setCommentaarWetgeving(CommentaarWetgeving value) {
        this.commentaarWetgeving = value;
    }

    /**
     * Gets the value of the geschiedenis property.
     * 
     * @return
     *     possible object is
     *     {@link Geschiedenis }
     *     
     */
    public Geschiedenis getGeschiedenis() {
        return geschiedenis;
    }

    /**
     * Sets the value of the geschiedenis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Geschiedenis }
     *     
     */
    public void setGeschiedenis(Geschiedenis value) {
        this.geschiedenis = value;
    }

    /**
     * Gets the value of the parlementair property.
     * 
     * @return
     *     possible object is
     *     {@link Parlementair }
     *     
     */
    public Parlementair getParlementair() {
        return parlementair;
    }

    /**
     * Sets the value of the parlementair property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parlementair }
     *     
     */
    public void setParlementair(Parlementair value) {
        this.parlementair = value;
    }

    /**
     * Gets the value of the eerstVerantwoordelijk property.
     * 
     * @return
     *     possible object is
     *     {@link EerstVerantwoordelijk }
     *     
     */
    public EerstVerantwoordelijk getEerstVerantwoordelijk() {
        return eerstVerantwoordelijk;
    }

    /**
     * Sets the value of the eerstVerantwoordelijk property.
     * 
     * @param value
     *     allowed object is
     *     {@link EerstVerantwoordelijk }
     *     
     */
    public void setEerstVerantwoordelijk(EerstVerantwoordelijk value) {
        this.eerstVerantwoordelijk = value;
    }

    /**
     * Gets the value of the materieleUitwerkingtredingDatum property.
     * 
     * @return
     *     possible object is
     *     {@link MaterieleUitwerkingtredingDatum }
     *     
     */
    public MaterieleUitwerkingtredingDatum getMaterieleUitwerkingtredingDatum() {
        return materieleUitwerkingtredingDatum;
    }

    /**
     * Sets the value of the materieleUitwerkingtredingDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaterieleUitwerkingtredingDatum }
     *     
     */
    public void setMaterieleUitwerkingtredingDatum(MaterieleUitwerkingtredingDatum value) {
        this.materieleUitwerkingtredingDatum = value;
    }

    /**
     * Gets the value of the origine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigine() {
        return origine;
    }

    /**
     * Sets the value of the origine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigine(String value) {
        this.origine = value;
    }

    /**
     * Gets the value of the grondslagen property.
     * 
     * @return
     *     possible object is
     *     {@link Grondslagen }
     *     
     */
    public Grondslagen getGrondslagen() {
        return grondslagen;
    }

    /**
     * Sets the value of the grondslagen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Grondslagen }
     *     
     */
    public void setGrondslagen(Grondslagen value) {
        this.grondslagen = value;
    }

    /**
     * Gets the value of the vertalingVan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vertalingVan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVertalingVan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VertalingVan }
     * 
     * 
     */
    public List<VertalingVan> getVertalingVan() {
        if (vertalingVan == null) {
            vertalingVan = new ArrayList<VertalingVan>();
        }
        return this.vertalingVan;
    }

    /**
     * Gets the value of the vertaaldDoor property.
     * 
     * @return
     *     possible object is
     *     {@link VertaaldDoor }
     *     
     */
    public VertaaldDoor getVertaaldDoor() {
        return vertaaldDoor;
    }

    /**
     * Sets the value of the vertaaldDoor property.
     * 
     * @param value
     *     allowed object is
     *     {@link VertaaldDoor }
     *     
     */
    public void setVertaaldDoor(VertaaldDoor value) {
        this.vertaaldDoor = value;
    }

    /**
     * Gets the value of the totstandkoming property.
     * 
     * @return
     *     possible object is
     *     {@link Totstandkoming }
     *     
     */
    public Totstandkoming getTotstandkoming() {
        return totstandkoming;
    }

    /**
     * Sets the value of the totstandkoming property.
     * 
     * @param value
     *     allowed object is
     *     {@link Totstandkoming }
     *     
     */
    public void setTotstandkoming(Totstandkoming value) {
        this.totstandkoming = value;
    }

    /**
     * Gets the value of the aliasTitels property.
     * 
     * @return
     *     possible object is
     *     {@link AliasTitels }
     *     
     */
    public AliasTitels getAliasTitels() {
        return aliasTitels;
    }

    /**
     * Sets the value of the aliasTitels property.
     * 
     * @param value
     *     allowed object is
     *     {@link AliasTitels }
     *     
     */
    public void setAliasTitels(AliasTitels value) {
        this.aliasTitels = value;
    }

    /**
     * Gets the value of the intitule property.
     * 
     * @return
     *     possible object is
     *     {@link Intitule }
     *     
     */
    public Intitule getIntitule() {
        return intitule;
    }

    /**
     * Sets the value of the intitule property.
     * 
     * @param value
     *     allowed object is
     *     {@link Intitule }
     *     
     */
    public void setIntitule(Intitule value) {
        this.intitule = value;
    }

    /**
     * Gets the value of the citeertitel property.
     * 
     * @return
     *     possible object is
     *     {@link Citeertitel }
     *     
     */
    public Citeertitel getCiteertitel() {
        return citeertitel;
    }

    /**
     * Sets the value of the citeertitel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Citeertitel }
     *     
     */
    public void setCiteertitel(Citeertitel value) {
        this.citeertitel = value;
    }

    /**
     * Gets the value of the wetBesluit property.
     * 
     * @return
     *     possible object is
     *     {@link WetBesluit }
     *     
     */
    public WetBesluit getWetBesluit() {
        return wetBesluit;
    }

    /**
     * Sets the value of the wetBesluit property.
     * 
     * @param value
     *     allowed object is
     *     {@link WetBesluit }
     *     
     */
    public void setWetBesluit(WetBesluit value) {
        this.wetBesluit = value;
    }

    /**
     * Gets the value of the regeling property.
     * 
     * @return
     *     possible object is
     *     {@link Regeling }
     *     
     */
    public Regeling getRegeling() {
        return regeling;
    }

    /**
     * Sets the value of the regeling property.
     * 
     * @param value
     *     allowed object is
     *     {@link Regeling }
     *     
     */
    public void setRegeling(Regeling value) {
        this.regeling = value;
    }

    /**
     * Gets the value of the circulaire property.
     * 
     * @return
     *     possible object is
     *     {@link Circulaire }
     *     
     */
    public Circulaire getCirculaire() {
        return circulaire;
    }

    /**
     * Sets the value of the circulaire property.
     * 
     * @param value
     *     allowed object is
     *     {@link Circulaire }
     *     
     */
    public void setCirculaire(Circulaire value) {
        this.circulaire = value;
    }

    /**
     * Gets the value of the verdrag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verdrag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerdrag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Verdrag }
     * 
     * 
     */
    public List<Verdrag> getVerdrag() {
        if (verdrag == null) {
            verdrag = new ArrayList<Verdrag>();
        }
        return this.verdrag;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link MetaData }
     *     
     */
    public MetaData getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaData }
     *     
     */
    public void setMetaData(MetaData value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the dtdversie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtdversie() {
        if (dtdversie == null) {
            return "2.0";
        } else {
            return dtdversie;
        }
    }

    /**
     * Sets the value of the dtdversie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtdversie(String value) {
        this.dtdversie = value;
    }

    /**
     * Gets the value of the sleutel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSleutel() {
        return sleutel;
    }

    /**
     * Sets the value of the sleutel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSleutel(String value) {
        this.sleutel = value;
    }

    /**
     * Gets the value of the soort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoort() {
        return soort;
    }

    /**
     * Sets the value of the soort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoort(String value) {
        this.soort = value;
    }

    /**
     * Gets the value of the labelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelId() {
        return labelId;
    }

    /**
     * Sets the value of the labelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelId(String value) {
        this.labelId = value;
    }

    /**
     * Gets the value of the stamId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStamId() {
        return stamId;
    }

    /**
     * Sets the value of the stamId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStamId(String value) {
        this.stamId = value;
    }

    /**
     * Gets the value of the versieId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersieId() {
        return versieId;
    }

    /**
     * Sets the value of the versieId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersieId(String value) {
        this.versieId = value;
    }

    /**
     * Gets the value of the verdragnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerdragnummer() {
        return verdragnummer;
    }

    /**
     * Sets the value of the verdragnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerdragnummer(String value) {
        this.verdragnummer = value;
    }

    /**
     * Gets the value of the publicatieAttr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicatieAttr() {
        return publicatieAttr;
    }

    /**
     * Sets the value of the publicatieAttr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicatieAttr(String value) {
        this.publicatieAttr = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
