//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:24 PM CEST 
//


package nl.wetten.bwbng.toestand;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}kop"/>
 *         &lt;element ref="{}wat" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;group ref="{}structuur.maximaal"/>
 *           &lt;element ref="{}wijzig-divisie"/>
 *           &lt;element ref="{}artikel"/>
 *           &lt;element ref="{}enig-artikel"/>
 *           &lt;element ref="{}wetcitaat"/>
 *           &lt;element ref="{}al-groep"/>
 *           &lt;element ref="{}divisie"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.wijzig-divisie"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kop",
    "wat",
    "structuurAlgemeenOrTableOrWijzigDivisie"
})
@XmlRootElement(name = "wijzig-divisie")
public class WijzigDivisie {

    @XmlElement(required = true)
    protected Kop kop;
    protected Wat wat;
    @XmlElementRefs({
        @XmlElementRef(name = "wijzig-divisie", type = WijzigDivisie.class, required = false),
        @XmlElementRef(name = "al-groep", type = AlGroep.class, required = false),
        @XmlElementRef(name = "enig-artikel", type = EnigArtikel.class, required = false),
        @XmlElementRef(name = "artikel", type = Artikel.class, required = false),
        @XmlElementRef(name = "structuur.algemeen", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "divisie", type = Divisie.class, required = false),
        @XmlElementRef(name = "table", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "wetcitaat", type = Wetcitaat.class, required = false)
    })
    protected List<Object> structuurAlgemeenOrTableOrWijzigDivisie;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "soort")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String soort;
    @XmlAttribute(name = "opmaak")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String opmaak;

    /**
     * Gets the value of the kop property.
     * 
     * @return
     *     possible object is
     *     {@link Kop }
     *     
     */
    public Kop getKop() {
        return kop;
    }

    /**
     * Sets the value of the kop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kop }
     *     
     */
    public void setKop(Kop value) {
        this.kop = value;
    }

    /**
     * Gets the value of the wat property.
     * 
     * @return
     *     possible object is
     *     {@link Wat }
     *     
     */
    public Wat getWat() {
        return wat;
    }

    /**
     * Sets the value of the wat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wat }
     *     
     */
    public void setWat(Wat value) {
        this.wat = value;
    }

    /**
     * Gets the value of the structuurAlgemeenOrTableOrWijzigDivisie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the structuurAlgemeenOrTableOrWijzigDivisie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStructuurAlgemeenOrTableOrWijzigDivisie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Formule }{@code >}
     * {@link JAXBElement }{@code <}{@link Lijst }{@code >}
     * {@link WijzigDivisie }
     * {@link AlGroep }
     * {@link EnigArtikel }
     * {@link JAXBElement }{@code <}{@link Plaatje }{@code >}
     * {@link Artikel }
     * {@link JAXBElement }{@code <}{@link Al }{@code >}
     * {@link Divisie }
     * {@link JAXBElement }{@code <}{@link Specificatielijst }{@code >}
     * {@link JAXBElement }{@code <}{@link Citaat }{@code >}
     * {@link JAXBElement }{@code <}{@link Adres }{@code >}
     * {@link JAXBElement }{@code <}{@link LokaalStructuurLiType }{@code >}
     * {@link Wetcitaat }
     * {@link JAXBElement }{@code <}{@link Definitielijst }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Adreslijst }{@code >}
     * {@link JAXBElement }{@code <}{@link Tussenkop }{@code >}
     * 
     * 
     */
    public List<Object> getStructuurAlgemeenOrTableOrWijzigDivisie() {
        if (structuurAlgemeenOrTableOrWijzigDivisie == null) {
            structuurAlgemeenOrTableOrWijzigDivisie = new ArrayList<Object>();
        }
        return this.structuurAlgemeenOrTableOrWijzigDivisie;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the soort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoort() {
        if (soort == null) {
            return "onbekend";
        } else {
            return soort;
        }
    }

    /**
     * Sets the value of the soort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoort(String value) {
        this.soort = value;
    }

    /**
     * Gets the value of the opmaak property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpmaak() {
        if (opmaak == null) {
            return "default";
        } else {
            return opmaak;
        }
    }

    /**
     * Sets the value of the opmaak property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpmaak(String value) {
        this.opmaak = value;
    }

}
