//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 02:36:24 PM CEST 
//


package nl.wetten.bwbng.toestand;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}lidnr"/>
 *         &lt;element ref="{}wat" minOccurs="0"/>
 *         &lt;element ref="{}wijziging" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.wijzig-lid"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lidnr",
    "wat",
    "wijziging"
})
@XmlRootElement(name = "wijzig-lid")
public class WijzigLid {

    @XmlElement(required = true)
    protected Lidnr lidnr;
    protected Wat wat;
    protected List<Wijziging> wijziging;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the lidnr property.
     * 
     * @return
     *     possible object is
     *     {@link Lidnr }
     *     
     */
    public Lidnr getLidnr() {
        return lidnr;
    }

    /**
     * Sets the value of the lidnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lidnr }
     *     
     */
    public void setLidnr(Lidnr value) {
        this.lidnr = value;
    }

    /**
     * Gets the value of the wat property.
     * 
     * @return
     *     possible object is
     *     {@link Wat }
     *     
     */
    public Wat getWat() {
        return wat;
    }

    /**
     * Sets the value of the wat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wat }
     *     
     */
    public void setWat(Wat value) {
        this.wat = value;
    }

    /**
     * Gets the value of the wijziging property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wijziging property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWijziging().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Wijziging }
     * 
     * 
     */
    public List<Wijziging> getWijziging() {
        if (wijziging == null) {
            wijziging = new ArrayList<Wijziging>();
        }
        return this.wijziging;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
