//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 02:04:00 PM CET 
//


package gov.loc.zing.srw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for explainResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="explainResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.loc.gov/zing/srw/}responseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}record"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}echoedExplainRequest" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}diagnostics" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}extraResponseData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "explainResponseType", propOrder = {
    "record",
    "echoedExplainRequest",
    "diagnostics",
    "extraResponseData"
})
public class ExplainResponseType
    extends ResponseType
{

    @XmlElement(required = true)
    protected RecordType record;
    protected ExplainRequestType echoedExplainRequest;
    protected DiagnosticsType diagnostics;
    protected ExtraDataType extraResponseData;

    /**
     * Gets the value of the record property.
     * 
     * @return
     *     possible object is
     *     {@link RecordType }
     *     
     */
    public RecordType getRecord() {
        return record;
    }

    /**
     * Sets the value of the record property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordType }
     *     
     */
    public void setRecord(RecordType value) {
        this.record = value;
    }

    /**
     * Gets the value of the echoedExplainRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ExplainRequestType }
     *     
     */
    public ExplainRequestType getEchoedExplainRequest() {
        return echoedExplainRequest;
    }

    /**
     * Sets the value of the echoedExplainRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExplainRequestType }
     *     
     */
    public void setEchoedExplainRequest(ExplainRequestType value) {
        this.echoedExplainRequest = value;
    }

    /**
     * Gets the value of the diagnostics property.
     * 
     * @return
     *     possible object is
     *     {@link DiagnosticsType }
     *     
     */
    public DiagnosticsType getDiagnostics() {
        return diagnostics;
    }

    /**
     * Sets the value of the diagnostics property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiagnosticsType }
     *     
     */
    public void setDiagnostics(DiagnosticsType value) {
        this.diagnostics = value;
    }

    /**
     * Gets the value of the extraResponseData property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraDataType }
     *     
     */
    public ExtraDataType getExtraResponseData() {
        return extraResponseData;
    }

    /**
     * Sets the value of the extraResponseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraDataType }
     *     
     */
    public void setExtraResponseData(ExtraDataType value) {
        this.extraResponseData = value;
    }

}
