//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 02:04:00 PM CET 
//


package gov.loc.zing.srw;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for searchRetrieveResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="searchRetrieveResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.loc.gov/zing/srw/}responseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}numberOfRecords"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}resultSetId" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}resultSetIdleTime" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}records" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}nextRecordPosition" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}echoedSearchRetrieveRequest" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}diagnostics" minOccurs="0"/>
 *         &lt;element ref="{http://www.loc.gov/zing/srw/}extraResponseData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchRetrieveResponseType", propOrder = {
    "numberOfRecords",
    "resultSetId",
    "resultSetIdleTime",
    "records",
    "nextRecordPosition",
    "echoedSearchRetrieveRequest",
    "diagnostics",
    "extraResponseData"
})
public class SearchRetrieveResponseType
    extends ResponseType
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfRecords;
    protected String resultSetId;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger resultSetIdleTime;
    protected RecordsType records;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger nextRecordPosition;
    protected EchoedSearchRetrieveRequestType echoedSearchRetrieveRequest;
    protected DiagnosticsType diagnostics;
    protected ExtraDataType extraResponseData;

    /**
     * Gets the value of the numberOfRecords property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfRecords() {
        return numberOfRecords;
    }

    /**
     * Sets the value of the numberOfRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfRecords(BigInteger value) {
        this.numberOfRecords = value;
    }

    /**
     * Gets the value of the resultSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultSetId() {
        return resultSetId;
    }

    /**
     * Sets the value of the resultSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultSetId(String value) {
        this.resultSetId = value;
    }

    /**
     * Gets the value of the resultSetIdleTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResultSetIdleTime() {
        return resultSetIdleTime;
    }

    /**
     * Sets the value of the resultSetIdleTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResultSetIdleTime(BigInteger value) {
        this.resultSetIdleTime = value;
    }

    /**
     * Gets the value of the records property.
     * 
     * @return
     *     possible object is
     *     {@link RecordsType }
     *     
     */
    public RecordsType getRecords() {
        return records;
    }

    /**
     * Sets the value of the records property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordsType }
     *     
     */
    public void setRecords(RecordsType value) {
        this.records = value;
    }

    /**
     * Gets the value of the nextRecordPosition property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNextRecordPosition() {
        return nextRecordPosition;
    }

    /**
     * Sets the value of the nextRecordPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNextRecordPosition(BigInteger value) {
        this.nextRecordPosition = value;
    }

    /**
     * Gets the value of the echoedSearchRetrieveRequest property.
     * 
     * @return
     *     possible object is
     *     {@link EchoedSearchRetrieveRequestType }
     *     
     */
    public EchoedSearchRetrieveRequestType getEchoedSearchRetrieveRequest() {
        return echoedSearchRetrieveRequest;
    }

    /**
     * Sets the value of the echoedSearchRetrieveRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link EchoedSearchRetrieveRequestType }
     *     
     */
    public void setEchoedSearchRetrieveRequest(EchoedSearchRetrieveRequestType value) {
        this.echoedSearchRetrieveRequest = value;
    }

    /**
     * Gets the value of the diagnostics property.
     * 
     * @return
     *     possible object is
     *     {@link DiagnosticsType }
     *     
     */
    public DiagnosticsType getDiagnostics() {
        return diagnostics;
    }

    /**
     * Sets the value of the diagnostics property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiagnosticsType }
     *     
     */
    public void setDiagnostics(DiagnosticsType value) {
        this.diagnostics = value;
    }

    /**
     * Gets the value of the extraResponseData property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraDataType }
     *     
     */
    public ExtraDataType getExtraResponseData() {
        return extraResponseData;
    }

    /**
     * Sets the value of the extraResponseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraDataType }
     *     
     */
    public void setExtraResponseData(ExtraDataType value) {
        this.extraResponseData = value;
    }

}
