//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 02:04:00 PM CET 
//


package gov.loc.zing.cql.xcql;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.loc.zing.cql.xcql package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Modifiers_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "modifiers");
    private final static QName _SearchClause_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "searchClause");
    private final static QName _Value_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "value");
    private final static QName _Term_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "term");
    private final static QName _Prefixes_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "prefixes");
    private final static QName _Boolean_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "boolean");
    private final static QName _LeftOperand_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "leftOperand");
    private final static QName _Prefix_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "prefix");
    private final static QName _Modifier_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "modifier");
    private final static QName _Type_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "type");
    private final static QName _Relation_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "relation");
    private final static QName _Identifier_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "identifier");
    private final static QName _Comparison_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "comparison");
    private final static QName _Index_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "index");
    private final static QName _Triple_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "triple");
    private final static QName _RightOperand_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "rightOperand");
    private final static QName _Name_QNAME = new QName("http://www.loc.gov/zing/cql/xcql/", "name");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.loc.zing.cql.xcql
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PrefixType }
     * 
     */
    public PrefixType createPrefixType() {
        return new PrefixType();
    }

    /**
     * Create an instance of {@link ModifierType }
     * 
     */
    public ModifierType createModifierType() {
        return new ModifierType();
    }

    /**
     * Create an instance of {@link ModifiersType }
     * 
     */
    public ModifiersType createModifiersType() {
        return new ModifiersType();
    }

    /**
     * Create an instance of {@link RelationType }
     * 
     */
    public RelationType createRelationType() {
        return new RelationType();
    }

    /**
     * Create an instance of {@link SearchClauseType }
     * 
     */
    public SearchClauseType createSearchClauseType() {
        return new SearchClauseType();
    }

    /**
     * Create an instance of {@link PrefixesType }
     * 
     */
    public PrefixesType createPrefixesType() {
        return new PrefixesType();
    }

    /**
     * Create an instance of {@link BooleanType }
     * 
     */
    public BooleanType createBooleanType() {
        return new BooleanType();
    }

    /**
     * Create an instance of {@link OperandType }
     * 
     */
    public OperandType createOperandType() {
        return new OperandType();
    }

    /**
     * Create an instance of {@link TripleType }
     * 
     */
    public TripleType createTripleType() {
        return new TripleType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifiersType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "modifiers")
    public JAXBElement<ModifiersType> createModifiers(ModifiersType value) {
        return new JAXBElement<ModifiersType>(_Modifiers_QNAME, ModifiersType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchClauseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "searchClause")
    public JAXBElement<SearchClauseType> createSearchClause(SearchClauseType value) {
        return new JAXBElement<SearchClauseType>(_SearchClause_QNAME, SearchClauseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "term")
    public JAXBElement<String> createTerm(String value) {
        return new JAXBElement<String>(_Term_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrefixesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "prefixes")
    public JAXBElement<PrefixesType> createPrefixes(PrefixesType value) {
        return new JAXBElement<PrefixesType>(_Prefixes_QNAME, PrefixesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BooleanType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "boolean")
    public JAXBElement<BooleanType> createBoolean(BooleanType value) {
        return new JAXBElement<BooleanType>(_Boolean_QNAME, BooleanType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperandType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "leftOperand")
    public JAXBElement<OperandType> createLeftOperand(OperandType value) {
        return new JAXBElement<OperandType>(_LeftOperand_QNAME, OperandType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrefixType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "prefix")
    public JAXBElement<PrefixType> createPrefix(PrefixType value) {
        return new JAXBElement<PrefixType>(_Prefix_QNAME, PrefixType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "modifier")
    public JAXBElement<ModifierType> createModifier(ModifierType value) {
        return new JAXBElement<ModifierType>(_Modifier_QNAME, ModifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "relation")
    public JAXBElement<RelationType> createRelation(RelationType value) {
        return new JAXBElement<RelationType>(_Relation_QNAME, RelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "identifier")
    public JAXBElement<String> createIdentifier(String value) {
        return new JAXBElement<String>(_Identifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "comparison")
    public JAXBElement<String> createComparison(String value) {
        return new JAXBElement<String>(_Comparison_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "index")
    public JAXBElement<String> createIndex(String value) {
        return new JAXBElement<String>(_Index_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TripleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "triple")
    public JAXBElement<TripleType> createTriple(TripleType value) {
        return new JAXBElement<TripleType>(_Triple_QNAME, TripleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperandType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "rightOperand")
    public JAXBElement<OperandType> createRightOperand(OperandType value) {
        return new JAXBElement<OperandType>(_RightOperand_QNAME, OperandType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/zing/cql/xcql/", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

}
